title: Project Page

fields:
  project_thumbnail:
    width: 1/3
    label: Projekt Vorschaubild
    type: files
    max: 1
    uploads:
      template: image
  project_description:
    label: Projekt Beschreibung
    type: writer
    width: 2/3
  project_link_list: fields/external_links

  content_rows:
    label: Reihen
    type: structure
    fields:
      content_columns:
        label: Spalten
        type: structure
        columns:
          content_type:
          content_width:
          content_background:
        max: 3
        fields:
          content_image:
            label: Bild
            type: files
            max: 1
            uploads:
              template: image
            when:
              content_type: content_image
          content_text:
            label: Text
            type: writer
            when:
              content_type: content_text
          content_type:
            width: 1/6
            label: Inhalts Typ
            type: select
            options:
              content_image: Bild
              content_text: Text
          content_width:
            width: 1/6
            label: Spalten Breite 
            type: select
            required: true
            options:
              1_1: 1/1
              1_6: 1/6
              1_3: 1/3
              1_2: 1/2
              2_3: 2/3
          content_background:
            width: 1/4
            label: Spalten Hintergrund 
            type: select
            options:
              red: Red
              green: Green
              blue: Blue


              


  